FROM golang:1.18.1
WORKDIR /go/src/app
ADD . /go/src/app
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN go get -u github.com/gin-gonic/gin
RUN go get -u gorm.io/gorm
RUN go get -u gorm.io/driver/mysql
RUN go get github.com/gin-contrib/sessions
EXPOSE 8080
CMD go run main.go